### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by leandroqm** [RocketChat/Docker.Official.Image#10]
Hello,

I am unable to use this image.
The box is a Debian 8 fully upgraded.

Info:

# docker run --name rocketchat --link rocketchatdb -d rocketchat/rocket.chat -ti
e7099b4a072358236e2930abc438af2643a89eba879e7640c398215ea697b219
Error response from daemon: Cannot start container e7099b4a072358236e2930abc438af2643a89eba879e7640c398215ea697b219: [8] System error: exec: "-ti": executable file not found in $PATH

19:54:18  ✘ ⚡  /data 
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

 19:55:31  ⚡  /data 
# docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED              STATUS              PORTS               NAMES
e7099b4a0723        rocketchat/rocket.chat   "-ti"                    About a minute ago   Created                                 rocketchat
1582f0c0ac95        mongo                    "/entrypoint.sh --sma"   6 minutes ago        Up 6 minutes        27017/tcp           rocketchatdb

**Comment by pierreozoux** [comment]
Hi,

you mixed arguments to docker run:
 1. you don't need `-it`
 2. even if you'd need, it is at the wrong place, should be before the image name. (after the image name, it is passed as arguments to the current entrypoint or as a superseed for cmd.
 3. you used the wrong name for the image

This should work:

```
docker run --name rocketchat --link rocketchatdb -d rocket.chat
```

If you have a runngin mongodb with the name `rocketchatdb`. (I close the issue because I'm sure it will solve it ;) )

**Comment by leandroqm** [comment]
Unfortunately, it did not solve the issue... :/

# docker run --name rocketchat --link rocketchatdb -d rocket.chat
Unable to find image 'rocket.chat:latest' locally
latest: Pulling from library/rocket.chat
709507467581: Pull complete 
8c59ab874855: Pull complete 
d4f67d857870: Pull complete 
e07234a19e6c: Pull complete 
10fde2a2f3ee: Pull complete 
5a506bbc1b6f: Pull complete 
9cc9fdcecba1: Pull complete 
02cf92cce9e8: Pull complete 
0ab1b987161e: Pull complete 
0e1b1f1bb12c: Pull complete 
Digest: sha256:719efbb59fd52379b91d294b13b39d8a14b06b3def47e3dd5b160563a423f5ae
Status: Downloaded newer image for rocket.chat:latest
Error response from daemon: Conflict. The name "rocketchat" is already in use by container e7099b4a0723. You have to remove (or rename) that container to be able to reuse that name.

 18:17:57  ✘ ⚡  /data 
# docker rm rocketchat
rocketchat

 18:18:08  ⚡  /data 
# docker run --name rocketchat --link rocketchatdb -d rocket.chat
00f79b385934f4620086c0953c5f02036b59b954358c1a3f3bbf21cfb6d89652

 18:18:17  ⚡  /data 
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
1582f0c0ac95        mongo               "/entrypoint.sh --sma"   22 hours ago        Up 22 hours         27017/tcp           rocketchatdb

 18:18:20  ⚡  /data 
#

**Comment by pierreozoux** [comment]
Did you read the error message?

```
Error response from daemon: Conflict. The name "rocketchat" is already in use by container e7099b4a0723. You have to remove (or rename) that container to be able to reuse that name.
```

It means a container is already running with that name. You need to stop it and remove it first.

I let you read the docker documentation to understand how to do it, and more than anything, to not copy my answer without understanding with the possibility for you to loose data.

**Comment by leandroqm** [comment]
Did you read all I posted?
I did just that, I removed the container first ... read it again, please.

**Comment by pierreozoux** [comment]
Arf sorry :)

try without the '-d' to see the error in your console.

**Comment by leandroqm** [comment]
Error: failed to connect to [db:27017]

maybe the link to rocketchatdb didnt work?

**Comment by pierreozoux** [comment]
yes exactly, make sure your mongo is working well and you can connect to it from another linked container.

Once you are sure of this, please try again and report here.

**Comment by leandroqm** [comment]
Using an external mongodb install, it works.
Thank you.
