### ISSUE TITLE
restore all data from other instance

### ISSUE THREAD

**Issue by spadazz** [RocketChat/Docker.Official.Image#105]
Hello, I have a snap rocketchat install (v 2.4.9) that I dumped via mongodump.
I transferred the dumped files in the docker server inside an import/dump folder, mounted inside the mongo container as /var/tmp/dump.
After the docker-compose startup, I went inside the mongo container & launched mongorestore from /var/tmp/dump.
Apparently it worked, but rocketchat is still showing only the default rooms/users/configs.
How can I transfer all data & configs from the old snap instance to the new docker one ?

Thanks

**Comment by Janevski** [comment]
Same thing happened to me as well...
snap export to docker, mongorestore went well from /var/dump, however rocket is showing me an installation wizzard.

The lession is, export-import rocket chat deployment is not a feature they'd like to develop.
I've red issues. It's been requested like since 2016.

**Comment by firlevapz** [comment]
actually you can find some nice walkthroughs how to move to another server or installation:

https://forums.rocket.chat/t/how-to-migrate-from-snap-to-manual-installed-rocketchat/2126
https://www.networktechguy.com/posts/post-0009/

After restoring the dump, still the setup-wizard showed up every time, but after setting the environment-variable `OVERWRITE_SETTING_Show_Setup_Wizard=completed` it finally worked (see
https://github.com/RocketChat/Rocket.Chat/issues/2233#issuecomment-459291066 )

**Comment by Janevski** [comment]
Is it completed, though?

**Comment by sampaiodiego** [comment]
the reason I closed this is because this is not a Rocket.Chat nor a Docker container issue, the original question seems to be related to misconfigured `MONGO_URL` env var..

**Comment by TiAldea** [comment]
When I was testing, I faced the same problem. I was able to fix it when I restored the Mongo backup beforehand. The Rocket container was up, but apparently, Rocket has a script that conflicts with mongorestore.
