### ISSUE TITLE
Not the official Dockerfile anymore

### ISSUE THREAD

**Issue by webwurst** [RocketChat/Docker.Official.Image#11]
DockerHub uses this one now:
https://github.com/RocketChat/Rocket.Chat/blob/develop/Dockerfile

Maybe you can state this in the Readme.

**Comment by pierreozoux** [comment]
Here is the official one.
https://hub.docker.com/_/rocket.chat/

But you are right, that we should remove: https://hub.docker.com/r/rocketchat/rocket.chat/
Or at least explain why there are 2?

**Comment by webwurst** [comment]
Ah! I see.. Yes please explain that at least on https://hub.docker.com/r/rocketchat/rocket.chat/ and link to the "real official one". At the moment it states there:
> "Official Rocket.Chat docker deployment image."

That somehow confused me.. ;) No idea who depends on that, maybe you could declare that as `deprecated` and remove after some time.

**Comment by Lednerb** [comment]
@engelgabriel @RocketChatApp 

You should really 'close' the deprecated / 'not really offical' repo at hub.docker.com.

Just pulled the 'wrong' one (https://hub.docker.com/r/rocketchat/rocket.chat/) and wondered why there's no documentation about hot to use it.

It seems that this is the right one:
https://hub.docker.com/r/library/rocket.chat/

**Comment by engelgabriel** [comment]
They both work the same way, there is no wrong/deprecated one.

**Comment by pierreozoux** [comment]
@engelgabriel I think it is a bit misleading to have 2 in the docker hub.
And indeed, you can see that both have 100k downloads. I think it would be a good idea to remove one of them.

What do you think?

**Comment by engelgabriel** [comment]
I don't think we have a develop tag on the image maintained by docker that we can generate a few times per day, can we?

And I don't think we can have venerability reports and participate on the partners program without the image maintained by docker, can we?

So I still believe we need both.

**Comment by pierreozoux** [comment]
Can we state it out loud:
 - the official is for prod
 - the other one is just for the development tag.

I think it is good to avoid confusion. I just close this issue as it is solved, but I let you keep that in mind :)

**Comment by geekgonecrazy** [comment]
Probably a good idea to mainly display the official one.  But yes if you want the develop tag you will have to use the one in our rocketchat account.  But both will remain completely valid for people to keep using.
