### ISSUE TITLE
3.2

### ISSUE THREAD

**Issue by xgdgsc** [RocketChat/Docker.Official.Image#111]
Please update to latest 3.2.

**Comment by luixxiul** [comment]
See: https://github.com/RocketChat/Docker.Official.Image/pull/108

**Comment by aminvakil** [comment]
3.2.1 came out too a few hours ago, but as it has just a bug fix for enterprise rocketchats, this repo can wait a few days I suppose before upgrading to 3.2.1 or just wait for next version.

**Comment by aminvakil** [comment]
Well it has waited a few days after 3.2.1 is out too.

**Comment by sampaiodiego** [comment]
closed by #108
