### ISSUE TITLE
install stable (not latest) for both rocket.chat and hubot using docker-compose

### ISSUE THREAD

**Issue by aleqx** [RocketChat/Docker.Official.Image#114]
What's the actual image name for the stable version? When looking at https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml it has `image: rocketchat/rocket.chat:latest` and `image: rocketchat/hubot-rocketchat:latest`

I'd like the stable version for both rather than latest.

p.s. your docs could use some updates and corrections as they are broken or misleading in some places

**Comment by sandrotanner** [comment]
If you want stable versions use the docker-compose.yml from this Repository ([RocketChat / Docker.Official.Image](https://github.com/RocketChat/Docker.Official.Image)).
The one you linked from the  [ RocketChat / Rocket.Chat ](https://github.com/RocketChat/Rocket.Chat) repository is for development.

so stable: `image: rocket.chat:latest`
not stable: `image: rocketchat/rocket.chat:latest`
