### ISSUE TITLE
Slack bridge error still exist in docker image version 3.4.2

### ISSUE THREAD

**Issue by Vinutha-Garimella** [RocketChat/Docker.Official.Image#116]
Hi, I see that this issue has been closed and code got merged to rocketchat repo, I created a rocketchat container from this image (rocket.chat:3.4.2) which was updated 10 hours ago in this website https://hub.docker.com/_/rocket-chat?tab=tags.

I am not able to connect rocket chat app to slack, when I enter the slack code and enable the slackbridge option in rocketchat app, I am getting following error in rocketchat container logs

![image](https://user-images.githubusercontent.com/33555892/88263092-16c8ee00-cce7-11ea-8f0b-7582220dfb6d.png)
Can anyone please let me know where am I going wrong.

**Comment by sampaiodiego** [comment]
as described on original issue (see comment https://github.com/RocketChat/Rocket.Chat/issues/17815#issuecomment-663023872) the fix will land on `3.5.0` release.

**Comment by Vinutha-Garimella** [comment]
@sampaiodiego  thanks for you reply, will check that image
