### ISSUE TITLE
3.7.0 - no curl in docker container

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Docker.Official.Image#124]
Hi,
In latest docker image 3.7.0 no curl is available.
In previous version was.
Without curl in container is hard to inspect some networks poroblems.
Could you add curl in next versions?

**Comment by sampaiodiego** [comment]
`curl` was actually removed on version 2.4.x

you can check previous comments on this matter on issue https://github.com/RocketChat/Docker.Official.Image/issues/107

closing this one as duplicated
