### ISSUE TITLE
High CPU load; Node proces

### ISSUE THREAD

**Issue by ParkHost** [RocketChat/Docker.Official.Image#125]
### Description:
High CPU load in docker Rocket.Chat container (not sure if it is normal behavior).
Proces is node and it is constantly 70% of CPU usage.
Am running it within 4 vcpu Ubuntu VPS

### Steps to reproduce:

Pull latest docker image
Run image as docker container

### Expected behavior:

CPU that time to time will spike, not constant high CPU load

### Actual behavior:

High CPU load

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Ubuntu 20.04 .1LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: Docker latest
- MongoDB Version: Docker latest

**Comment by sampaiodiego** [comment]
seems related to https://github.com/RocketChat/Rocket.Chat/issues/19082

can you please run with the following environment variable set and see if it help?
`USE_NATIVE_OPLOG=true`

**Comment by ParkHost** [comment]
yep this solved the high cpu issue, thanks!

**Comment by sampaiodiego** [comment]
good to know, thanks.. 

FYI there is a fox this already https://github.com/RocketChat/Rocket.Chat/pull/19181

once that is merged we'll launch a 3.7.1 release so you won't need to env var anymore.

**Comment by codeneno** [comment]
@sampaiodiego 
Does this only fix "mmapv1 database engine or when no admin access was granted to the database user,"?
we use 3.3.3 version,and it will have a high cpu load sometimes,does this work for wiredTiger ?thank you.
