### ISSUE TITLE
Please provide 3.8.3 image

### ISSUE THREAD

**Issue by col-panic** [RocketChat/Docker.Official.Image#127]
Considering that due to 'Exception on certain login cases including SAML' multilple old versions were
updated, the official docker releases should also be updated to this state.

Could you please provide an updated 3.8.3 docker image?

**Comment by sampaiodiego** [comment]
Closed by https://github.com/RocketChat/Docker.Official.Image/commit/648c6d66da0421a344368c8861285bbf83590c7a

later today I'll open a pull request to Docker libraries to add the 3.8 image.. thx
