### ISSUE TITLE
New Rocket.Chat versions missing in the docker hub

### ISSUE THREAD

**Issue by cs35-owncloud** [RocketChat/Docker.Official.Image#133]
Hello,

I've noticed that newest versions of Rocket.Chat are not on the [docker hub](https://hub.docker.com/_/rocket-chat?tab=tags&page=1&ordering=last_updated) (3.10.4 or the brand new 3.10.5), could you update it ?
Thanks.

**Comment by nexus166** [comment]
![DYI?](https://media.giphy.com/media/l0Ex6LbzSMtDOxAwU/giphy.gif)

**Comment by cs35-owncloud** [comment]
@nexus166 I doubt I can update myself the official DockerHub of Rocket.Chat.
We already came across this "issue" several times:

* https://github.com/RocketChat/Docker.Official.Image/issues/127
* https://github.com/RocketChat/Docker.Official.Image/issues/119
* https://github.com/RocketChat/Docker.Official.Image/issues/111

Nevertheless, thanks for your answer.

**Comment by szampardi** [comment]
Obviously and luckily not anyone can push to the official dockerhub repo but what prevents you from doing just the docker build and running the result?

**Comment by nexus166** [comment]
Obviously/luckily not everyone can push images to the official dockerhub repo, but what stops you from building the new image yourself while you wait?

**Comment by cs35-owncloud** [comment]
Obviously I could, it's not my question ... I'd rather prefer stick to an official release, I doubt it's interesting to reinvent the wheel.
My point is just that releases could be uploaded directly to the Dockerhub when it's out, it would be easier to any kind of user.
Lastly, it could be possible that the upload was forgotten on the Dockerhub.
But sure, answering only with a gif is a way to go.

**Comment by sampaiodiego** [comment]
thx guys, for you comments.. in this case, we were in investigating possible issues affecting 3.10 performance, so we didn't release an update..

but as per yesterday's releases, I'll updating  all versions here ASAP

**Comment by cs35-owncloud** [comment]
Hello @sampaiodiego 

thanks for your feedback, sorry for the issue the goal wasn't to be a bother but only to know if it could be updated, I had no idea about the possible performance issue. Way too impatient :'D
Thanks for your work ! :)
