### ISSUE TITLE
Dockerhub rocketchat/rocket.chat:latest suddenly pointing to 3.14.5 instead of 3.15.0

### ISSUE THREAD

**Issue by capi** [RocketChat/Docker.Official.Image#142]
After pulling `latest` today (via both registry.rocket.chat or docker hub), the latest failed to start since it could not find migration 215. Checking the various tags on docker-hub shows that `latest` now points to 3.14.5 instead of 3.15.0, since it seems to have been pushed later.

![image](https://user-images.githubusercontent.com/254852/121007098-f5071700-c791-11eb-8636-eef9328b5b85.png)

I think `latest` should always point to the latest of the current stable branch, shouldn't it?

**Comment by sampaiodiego** [comment]
thanks @capi for poiting that out.. you're right and it is now fixed. it is an issue with our current CI that always publishes the last release as latest, but just like it happened this time, it is not always the case.
