### ISSUE TITLE
Mirgation error in version 3.15.0, i probably used an early/broke docker image

### ISSUE THREAD

**Issue by ParkHost** [RocketChat/Docker.Official.Image#143]
3.15.0 broke my RC config.

```
Exception in callback of async function: errorClass [Error]: [Can't find migration version 225]
  isClientSafe: true,
  error: "Can't find migration version 225",
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

**Comment by ParkHost** [comment]
i reverted the image back to 3.14.4 and set in mongodb > DB:rocketchat > db.migrations.update({"_id": "control"}, {$set:{"version": 222}})

RC should now boot up again in the old version.
Now do your upgrade again and it should work, at least it worked for me.

**Comment by sampaiodiego** [comment]
that was probably an issue with the `latest` tag we had yesterday.. I apologize for that. the `latest` tag is pointing to 3.15.0 again
