### ISSUE TITLE
link to dockerhub is wrong...... maybe

### ISSUE THREAD

**Issue by stefanocudini** [RocketChat/Docker.Official.Image#152]
link in this repo details:
https://hub.docker.com/_/rocket.chat/

this is the result  searching on dockerhub:
https://hub.docker.com/_/rocket-chat/

(minus instead dot)

**Comment by sampaiodiego** [comment]
good catch @stefanocudini .. I've fixed it.. thx

**Comment by sandrotanner** [comment]
https://github.com/RocketChat/Docker.Official.Image/issues/110
