### ISSUE TITLE
[question] where is the log file?

### ISSUE THREAD

**Issue by changsijay** [RocketChat/Docker.Official.Image#16]
I run rocketchat docker container, follow the README and running now.
I am not sure where can I know something like who login, logout event log.
Can it be specify in the command line?
Thanks.

**Comment by jekuno** [comment]
Did you try `docker logs rocketchat`?

**Comment by mabushey** [comment]
If you;re using docker-compose, it would be `docker logs -f docker_rocketchat_1`

**Comment by geekgonecrazy** [comment]
Like others said you can access with docker logs. 

But to answer your question specifically... logs do not goto file.  It logs to stdout
