### ISSUE TITLE
New releases missing

### ISSUE THREAD

**Issue by Montg0mery** [RocketChat/Docker.Official.Image#162]
The latest release of Rocket.Chat is 4.8.1, but the latest official Docker image on https://hub.docker.com/_/rocket-chat/ is 4.6.3.

Please can you push the latest versions?

Thank you.

**Comment by belmeopmenieuwesim** [comment]
See: https://hub.docker.com/r/rocketchat/rocket.chat/tags/

**Comment by Montg0mery** [comment]
> See: https://hub.docker.com/r/rocketchat/rocket.chat/tags/

So is the one I linked to that is called "rocket.chat" and has a "Docker Official Image" label on it an imposter?

**Comment by belmeopmenieuwesim** [comment]
No, I believe the one you linked is an official docker image, meaning it is maintained by Docker itself. So it will always have a delay, since the maintainers of RocketChat use https://hub.docker.com/r/rocketchat/rocket.chat/tags/

**Comment by daberkow** [comment]
Looks like we are up to date now!

**Comment by sampaiodiego** [comment]
new updates are now published.. there is also a new automation to help keep them updated https://github.com/RocketChat/Docker.Official.Image/commit/64a2d0086477d2dae7bada6df87a6a0fe34708b6
