### ISSUE TITLE
blank screen after upgrade 4.8.2 to 5.0.0

### ISSUE THREAD

**Issue by kirill0174** [RocketChat/Docker.Official.Image#168]
i see gray blank screen after upgrade rocketchat 4.8.2 to 5.0.0 (via docker)
![image](https://user-images.githubusercontent.com/110159556/181453303-21c85451-9c5b-43a2-a5d2-f51ce40e583c.png)
![image](https://user-images.githubusercontent.com/110159556/181453368-4653a34c-a329-48d6-8b3d-84ab627f7003.png)

mongo version 5.0.9
no have errors in containers logs. Only errors in browser console
![image](https://user-images.githubusercontent.com/110159556/181453943-fe741248-8c05-428e-b039-f6b48a13a7a6.png)
![image](https://user-images.githubusercontent.com/110159556/181454009-e4f484a5-7ab8-4468-b928-be4b9972af89.png)

**Comment by kirill0174** [comment]
nothing working even on clear servers. A installed new instances with clean mongodb and got same errors
![image](https://user-images.githubusercontent.com/110159556/181721661-54e3bf96-79f6-498b-aa1b-b45395744099.png)

**Comment by sandrotanner** [comment]
Did you add the `directConnection=true` part to the mongo URLs?

see under "important notes": https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0

**Comment by debdutdeb** [comment]
This is a product bug https://github.com/RocketChat/Rocket.Chat/issues/26379

@sandrotanner not needed with the new compose file. 

Closing this. Please follow the progression in the linked issue. Fix will be released in 5.0.2.
