### ISSUE TITLE
MongoDB does not Persist after Restart (Default Compose File Issue)

### ISSUE THREAD

**Issue by lemongarbage** [RocketChat/Docker.Official.Image#171]
I noticed in the `docker-compose.yml` that, for the volume, the default MongoDB named volume is used. This is not desirable since data **does not persist after bringing down the containers** as per Bitnami's own documentation :

![image](https://user-images.githubusercontent.com/26641574/185223007-f3df1330-02ea-459a-bd0b-307f7d9649a0.png)

The Rocket.Chat documentation also neglects to mention this. While it should be the responsibility of the User to know how Docker containers ultimately function, I think the documentation should at least _mention_ that data does not persist, if not provide the configuration to do so.

**Comment by sampaiodiego** [comment]
the new compose file uses a volume now.. thx
