### ISSUE TITLE
Invalid interpolation format for "rocketchat" option in service "services": "registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}"

### ISSUE THREAD

**Issue by iTimELeZz** [RocketChat/Docker.Official.Image#180]
Hey I am trying to setup a docker container with Rocketchat and got the method with a "REG_TOKEN" but even with all prerequisites that are required I get that error..  

`ERROR: Invalid interpolation format for "rocketchat" option in service "services": "registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}"`

Docker is installed on a virtualised ubuntu live server with version 20.04

**Comment by shane51** [comment]
same issue, seems docker-compose cli bug, I upgraded docker-compose to v2.15.1, it works

**Comment by dudanogueira** [comment]
You have an old docker and docker compose version.

Those are the version I use:

duda.nogueira@rocket.chat:~$ docker --version
Docker version 23.0.1, build a5ee5b1

duda.nogueira@rocket.chat:~$ docker compose version
Docker Compose version v2.16.0

Notice, on newer versions you should use `docker compose`, instead of `docker-compose`

**Comment by jhonnasi** [comment]
> Notice, on newer versions you should use docker compose, instead of docker-compose

Important! thanks!

**Comment by Kantana96** [comment]
> You have an old docker and docker compose version.
> 
> Those are the version I use:
> 
> [duda.nogueira@rocket.chat](mailto:duda.nogueira@rocket.chat):~$ docker --version Docker version 23.0.1, build a5ee5b1
> 
> [duda.nogueira@rocket.chat](mailto:duda.nogueira@rocket.chat):~$ docker compose version Docker Compose version v2.16.0
> 
> Notice, on newer versions you should use `docker compose`, instead of `docker-compose`

your answer solved my issue, I used 'docker compose' instead of 'docker-compose'.
