### ISSUE TITLE
Image for Version 5.4.3

### ISSUE THREAD

**Issue by TF-R** [RocketChat/Docker.Official.Image#181]
In version 5.4.3 a Security Issue was fixed.

In https://hub.docker.com/_/rocket-chat there is only 5.4.0 available

We would be very happy if an image for this version would be build.

**Comment by dudanogueira** [comment]
**Hi! Sorry for the delay here :(**

All images are always in the **official** repository:

**https://hub.docker.com/r/rocketchat/rocket.chat/**

Also, you can always use, as an image:

registry.rocket.chat/rocketchat/rocket.chat:`tag_name_here`

So you can avoid docker hub traffic limitations.
