### ISSUE TITLE
No docker images beyond 6.0.0?

### ISSUE THREAD

**Issue by jalbstmeijer** [RocketChat/Docker.Official.Image#191]
Any reason versions 6.0.5 and 6.1.5 are not available yet at dockerhub?

**Comment by WebsliceNL** [comment]
I meant https://hub.docker.com/_/rocket-chat/
Am I expected to switch to https://hub.docker.com/r/rocketchat/rocket.chat ?

**Comment by fhloston** [comment]
I have also wondered about the purpose of this "Docker Official Image" which as of today still has 6.0.0 as latest version.

At the same time you get an email from the Rocket CEO nudging you to upgrade to 6.1.6 - which is not available as "Docker Official Image".

**Comment by debdutdeb** [comment]
rocketchat/rocket.chat **is** our official image. And is **always** pushed the same day within a couple hours of release.

**Comment by debdutdeb** [comment]
> Am I expected to switch to https://hub.docker.com/r/rocketchat/rocket.chat ?

@WebsliceNL yes, please. We have been asking folks to move to that image for a long time now. In all of our sources, we refer to that image and not the docker library one (more specifically registry.rocket.chat/rocketchat/rocket.char image)

**Comment by sandrotanner** [comment]
![image](https://github.com/RocketChat/Docker.Official.Image/assets/1583259/1f33dc07-3d7f-49e4-b83f-cc04bd90799b)
@debdutdeb  Maybe updateing the link in the repo would help... ;)

**Comment by jalbstmeijer** [comment]
> > Am I expected to switch to https://hub.docker.com/r/rocketchat/rocket.chat ?
> 
> @WebsliceNL yes, please. We have been asking folks to move to that image for a long time now. In all of our sources, we refer to that image and not the docker library one (more specifically registry.rocket.chat/rocketchat/rocket.char image)

@debdutdeb , must have missed that memo or I never read the documentation. Maybe an Idea to publish this wish on the https://hub.docker.com/_/rocket-chat/ page?. Switched last week to the new repo and all went fine.

**Comment by debdutdeb** [comment]
We'll be combing through everything and make sure this is clearer and consistent, including any technical clarifications. 

Docker official is basically an image that is in the official docker account. Not rocketchat's official image. That's where the confusion begins. Keeping that in mind we'll also rename the repo and change any documentation related to that. 

Can't share more details as I don't have them right now either. I'm actually visiting some relatives and commenting in between. Once I'm back tomorrow, and discussed with the team, I'll share more details here on the path we'll be taking to make this not confusing. 

Until then, registry.rocket.chat/rocketchat/rocket.chat is **our** official image, and what is recommended to use. 

Hope this helps :)
