### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by GuShaocheng** [RocketChat/Docker.Official.Image#194]
Hi,

I am kindly asking how to update RocketChat. It reminds me every time to update. But when I go to the compose.yml file on my Ubuntu server, it is marked as the 'latest' release (see below). So I wonder why it doesn't update after I stop the running container and run `docker compose up -d` again.

I appreciate your help!

##########compose.yml############
`volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-4.4}
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
`

**Comment by im-ecorp** [comment]
Hello to you,
I had the same problem as you.
What is available now is version 6.3, which is not recommended.  I installed version 5.4, and it worked properly.  The bug that version 6.4 has is that it gets stuck on the loading page and gives the following error![IMG_20231002_125142_964.png](https://github.com/RocketChat/Docker.Official.Image/assets/22276898/04ed64cf-84f6-4308-8112-2975a068c1f5)

**Comment by asheroto** [comment]
I don't understand why the team doesn't keep this up-to-date. Seems like the Docker releases are very delayed.

**Comment by sampaiodiego** [comment]
new updates are now published.. there is also a new automation to help keep them updated https://github.com/RocketChat/Docker.Official.Image/commit/64a2d0086477d2dae7bada6df87a6a0fe34708b6
