### ISSUE TITLE
Image is using an EOL version of NodeJS

### ISSUE THREAD

**Issue by LaurentGoderre** [RocketChat/Docker.Official.Image#197]
The image is using Node version 14 which is 2 LTS version behind. It would be ideal if the image could support multiple runtime of NodeJS to facilitate the update to the runtime environment.

**Comment by sandrotanner** [comment]
100% agree.
I think the issue is on meteors side but if I recall correctly they provide a extended support for node 14. Rocket should address and/or communicate that

**Comment by LaurentGoderre** [comment]
Linking upstream issue: https://github.com/meteor/meteor/discussions/12015

**Comment by sampaiodiego** [comment]
rocket.chat 7.0 now uses NodeJS 20
