### ISSUE TITLE
No updates since 6.4.2 release?

### ISSUE THREAD

**Issue by TermeHansen** [RocketChat/Docker.Official.Image#201]
Why don't we get any docker updates since 6.4.2?
https://hub.docker.com/_/rocket.chat

As of yesterday we are on 6.5.0, but since 6.4.2 we have had point releases up to 6.4.8 also, but not on the docker release?!?

**Comment by mickymiek** [comment]
Bumping, we need a bug fix that made it in 6.4.4 here.

**Comment by sampaiodiego** [comment]
new updates are now published.. there is also a new automation to help keep them updated https://github.com/RocketChat/Docker.Official.Image/commit/64a2d0086477d2dae7bada6df87a6a0fe34708b6
