### ISSUE TITLE
Need to get new releases out faster.

### ISSUE THREAD

**Issue by christ** [RocketChat/Docker.Official.Image#211]
There are multiple old issues commenting on the same issue, the latest image is behind by many versions. What can we do about getting this official image updated quicker?

**Comment by thomasklosinsky** [comment]
Same here!

**Comment by thomasklosinsky** [comment]
use rocketchat/rocket.chat ... that has all the latest Upgrades included.

**Comment by sandrotanner** [comment]
or build your own using the release API https://releases.rocket.chat/latest/info

**Comment by oussjarrousse** [comment]
> use rocketchat/rocket.chat ... that has all the latest Upgrades included.

what is the difference between those repositories?

**Comment by sampaiodiego** [comment]
sorry guys for any trouble.. there is a new automation to help publishing new versions faster https://github.com/RocketChat/Docker.Official.Image/commit/64a2d0086477d2dae7bada6df87a6a0fe34708b6
