### ISSUE TITLE
Docker image User not found

### ISSUE THREAD

**Issue by mremptypants** [RocketChat/Docker.Official.Image#215]
Old connections that are logged are still good, but when trying to update setting in the admin or even login to the web portal it goes user not found.

All the messages are still there, setting and everything but it is like the database dropped the users. I can not seem the find a answer or anything on this. 

I can reload the docker, update all the setting to match the new settings in the new compose, use old setting, tried it all and it worked fine in the 6.lastest release. 

Any ideas or help would be great.

**Comment by sampaiodiego** [comment]
all data is stored in MongoDB.. you didn't provide details on your deployment, but make sure you're using the `MONGO_URL` as you used before, you'll find the DB name in there, so if you changed it for some reason, the db will look empty.

**Comment by mremptypants** [comment]
@sampaiodiego plus why did you close this....

**Comment by mremptypants** [comment]
Right... But yet it was working fine 6.13 updated to 7.0 and dame broken...and if that is the case why would it work than not in 7.0. There is no configuration that would not let new users work fine yet old users get that error..being that are showing in the same tablesin the database but OK than.
