### ISSUE TITLE
bash is absent from the 7.0.0 image

### ISSUE THREAD

**Issue by Inspirational-sausage-dog** [RocketChat/Docker.Official.Image#217]
Hello.

Trying to launch a custom bash script into rocket chat 7.0.0. based container in docker on Ubuntu 22.04. 

Bash seems to be absent from the image, so docker-entrypoint.sh treats it as argument and fallbacks on nodejs which produces the following error:

> Error: Cannot find module ‘/app/bundle/bash’

Debian upstreams from both versions seem to contain it. Is there a specific reason why bash is absent from the image? If it's an unexpected behavior, could you please look into it?

It is a possibility that this issue occured on previous releases as well:

https://help.egroupware.org/t/rocketchat-error-cannot-find-module-app-bundle-bash/78389

With regards,

**Comment by sampaiodiego** [comment]
can you pls explain how are you using the image? we don't have a `docker-entrypoint.sh` file, so I wonder where is this coming from and what does it do

**Comment by Inspirational-sausage-dog** [comment]
Perhaps I am using wrong image? Is registry.rocket.chat/rocketchat/rocket.chat the right repository?

You can inspect the entrypoint using inspect subcommand and this repository has one:
```
sudo docker inspect registry.rocket.chat/rocketchat/rocket.chat:7.0.0 | jq .[].Config.Entrypoint
[
  "docker-entrypoint.sh"
]

sudo docker run --rm registry.rocket.chat/rocketchat/rocket.chat:6.6.2 which docker-entrypoint.sh
/usr/local/bin/docker-entrypoint.sh
```

I am using image in a this manner
```
services:            
  rocketchat:       
    image: registry.rocket.chat/rocketchat/rocket.chat:7.0.0
    command: >
      bash -c                   
       "< custom script here >"

...
```

But even manually you can guess that an entrypoint script is in use:

```
sudo docker pull registry.rocket.chat/rocketchat/rocket.chat:7.0.0
sudo docker run --rm registry.rocket.chat/rocketchat/rocket.chat:7.0.0 not_command_string


node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '/app/bundle/not_command_string'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.17.0
```

**Comment by debdutdeb** [comment]
We switched to alpine as the base for our official image starting 7.0.0. Due to this, bash is missing. If your script is posix compliant, you should be able to simply replace bash with ash or sh. Or you'll need to migrate to either of those shells.

Closing for now as this isn't a bug.

**Comment by Inspirational-sausage-dog** [comment]
Thank you for your answe. I wish Dockerfile would represent this switch of upstreams.

**Comment by sampaiodiego** [comment]
@Inspirational-sausage-dog you can still use the debian variant that is available at `registry.rocket.chat/rocketchat/rocket.chat:7.0.0-debian`
