### ISSUE TITLE
imagemagick - graphicsmagick

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Docker.Official.Image#23]
I just noticed that our image is not complete, it misses this library. Would you like me to PR to add it? should I add imagemagick or graphicsmagick ?

**Comment by geekgonecrazy** [comment]
I believe we took out imagemagick when we looked at the Docker scan and saw the version we were using was vulnerable.  So we just need to make sure we add one that isn't vulnerable.

**Comment by pierreozoux** [comment]
Let's keep it simple, and not ship it.
