### ISSUE TITLE
Running in a sub folder

### ISSUE THREAD

**Issue by bschueller** [RocketChat/Docker.Official.Image#30]
Hi there,

i'm trying to run RocketChat as a docker container with reverse proxy in a sub folder (https://001docker2t/rocketchat).
My problem is that file upload is using the wrong url (https://001docker2t/ufs/...) and stay at 0%.

Docker calls:
docker run --name rocketchatdb --restart unless-stopped -d -v /var/docker/rocketchat/db:/data/db mongo:3.0 --smallfiles
docker run --name rocketchat --restart unless-stopped -p 172.17.0.1:3000:3000 --link rocketchatdb --env ROOT_URL=https://001docker2t/rocketchat/ --env MONGO_URL=mongodb://rocketchatdb:27017/meteor  -d rocket.chat

As in the documentation for sub folders (https://rocket.chat/docs/installation/manual-installation/running-in-a-sub-folder) i set the ROOT_URL to https://001docker2t/rocketchat/. In the application i set under Admin > General only the domain.

Do i have a wrong configuration or is there something wrong with uploads using subfolders?

Versions:
NODE_VERSION	4.8.1
YARN_VERSION	0.21.3
RC_VERSION	0.54.0

**Comment by bschueller** [comment]
Has anyone reviewed my problem yet? Or are there any questions?

**Comment by steffen-kdab** [comment]
I have exactly the same problem.

**Comment by PPPBerlin** [comment]
Please review this problem. Assets and avatar upload works well with the subfolder, but not the file upload in chats.

**Comment by borgiani** [comment]
I have this problem only when using the MacOS Rocket.Chat+ client. Via the web interface it works just fine.
RC version 0.58.4

**Comment by geekgonecrazy** [comment]
This is definitely supported.  Please see docs if any have issues with this.  Not specific to this docker image at all.

Closing
