### ISSUE TITLE
Keyserver issues

### ISSUE THREAD

**Issue by ToeiRei** [RocketChat/Docker.Official.Image#34]
[ha.]pool.sks-keyservers.net seems to have a IPv4 vs. IPv6 thing: GPG's dirmngr might select a v6 server from the pool and try to connect to it, even though it doesn't have v6 connectivity inside the container. So build fails every now and then.

(could be this bug: https://bugs.launchpad.net/ubuntu/+source/gnupg2/+bug/1625845)

If one wants stay with sks-keyservers, ipv4.pool.sks-keyservers.net can be used.

**Comment by geekgonecrazy** [comment]
This should be resolved
