### ISSUE TITLE
ImageMagick or GraphicsMagick can not be found

### ISSUE THREAD

**Issue by ezdub19** [RocketChat/Docker.Official.Image#39]
I have got Rocket.Chat up and running on Plesk Onyx (ubuntu 16.04.3) using the docker system by running these commands.

docker run --name db -d mongo:3.0 --smallfiles

docker run --name rocketchat --link db -d rocket.chat

Everything is working accept the Avatar Resize which is giving and error:
'The image resize will not work because we can not detect ImageMagick or GraphicsMagick installed on your server.'

I have both installed on the server but for some reason it's not being detected by Rocket.Chat.

Am I missing something?

![2018-01-07_01-00-42](https://user-images.githubusercontent.com/35177245/34645482-81a95746-f346-11e7-8570-c07a2f3b1770.jpg)

The other issue I get is when I go into the docker settings I have to change  Accounts_AvatarStorePath to  ACCOUNTS_AVATARSOREPATH and remove  Accounts_AvatarStorePath otherwize I get an error about lowercase letters.

**Comment by ezdub19** [comment]
Final figured it out there seems to be an issue with this Docker image. As it works perfectly on the other official one.

**Comment by geekgonecrazy** [comment]
Neither are used any more.  Closing
