### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by robrotheram** [RocketChat/Docker.Official.Image#4]
Try running the commands listed on the read me but getting the error

    Error: image library/rocket.chat:latest not found

commands run

    docker run --name db -d mongo mongod --smallfiles
    docker run --name rocketchat --env ROOT_URL=http://robrotheram.com --link db rocket.chat

Tried replacing it with

    docker run --name rocketchat --env ROOT_URL=http://robrotheram.com --link db rocketchat/rocket.chat

to pull from the docker repository but then getting the error 

    Status: Downloaded newer image for rocketchat/rocket.chat:latest
    => Starting meteor app on port:80

    /built_app/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
    Error: MONGO_URL must be set in environment
        at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
        at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
        at new Mongo.Collection (packages/mongo/collection.js:98:1)
        at packages/accounts-base/accounts_common.js:141:1
        at /built_app/programs/server/packages/accounts-base.js:243:4
        at /built_app/programs/server/packages/accounts-base.js:1659:3
        at /built_app/programs/server/boot.js:222:10
        at Array.forEach (native)
        at Function._.each._.forEach          (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /built_app/programs/server/boot.js:117:5

**Comment by Sing-Li** [comment]
@robrotheram  - sorry, you're ahead of us by about a week :)

This is work-in-progress.

Please following this working instructions instead ....

https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux

**Comment by xxedgexx** [comment]
Tried this.  I receive:

Attaching to genericlinux_db_1, genericlinux_web_1
db_1  | 2015-07-29T19:14:07.281+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
db_1  | 2015-07-29T19:14:07.351+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
web_1 | => Starting meteor app on port:80
web_1 | 
web_1 | /built_app/programs/server/node_modules/fibers/future.js:278
web_1 | 						throw(ex);
web_1 | 						      ^
web_1 | Error: failed to connect to [db:27017]
web_1 |     at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
web_1 |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
web_1 |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
web_1 |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
web_1 |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
web_1 |     at new Mongo.Collection (packages/mongo/collection.js:98:1)
web_1 |     at packages/accounts-base/accounts_common.js:141:1
web_1 |     at /built_app/programs/server/packages/accounts-base.js:243:4
web_1 |     at /built_app/programs/server/packages/accounts-base.js:1659:3
web_1 |     at /built_app/programs/server/boot.js:222:10

**Comment by robrotheram** [comment]
@xxedgexx I found a work around
1: clone this repo
2: cd into the repo
3: run the command "docker build -t rocket.chat ." this will use this docker file to build a image
4: run the other commands  in the readme  and it should start

**Comment by xxedgexx** [comment]
Thanks.  I'll give that a try.

**Comment by Sing-Li** [comment]
@robrotheram  :+1:

**Comment by donoftime** [comment]
In addition to @robrotheram's helpful procedure to generate a container with the most recent source code, I also found that I needed to change a couple of values from what is shown in the README. This resulted in a slightly modified command for running the rocketchat container:

```sh
docker run --name rocketchat -p 80:80 --env ROOT_URL=http://<host> --env MONGO_URL=mongodb://db:27017/meteor --link db -d rocket.chat
```

The first modification, which is more directly related to our mongo error messages, is to explicitly specify the value of the MONGO_URL to use. This can be done by modifying the environment, just like we do for the [ROOT_URL](https://github.com/RocketChat/Docker.Official.Image#how-to-use-this-image). That is the purpose of the added:

```
--env MONGO_URL=mongodb://db:27017/meteor
```

The second modification was a misunderstanding I stumbled over regarding the port that is used. I assumed, just as the README did, that the port inside the container that we needed to forward was going to be 3000 (the normal default for a meteor app). However it seems someone already switched it to 80 for us, so we should be forwarding 80 in the container to 80 on the host with:

```
-p 80:80
```

I caught that anomaly by looking at `docker logs rocketchat`, which had this helpful message at the beginning:

```
=> Starting meteor app on port:80
```

Hopefully that helps a bit if you don't have it already, @xxedgexx

**Comment by Sing-Li** [comment]
It should work now.  We're official.

**Comment by xxedgexx** [comment]
Is there any docker-compose env's that can be used to configure LDAP?

**Comment by Sing-Li** [comment]
The official image is 0.4, which I think already support LDAP - but I might be wrong.

This one will always pull the latest commit:

https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux

And then you follow these instructions.

https://github.com/RocketChat/Rocket.Chat/wiki/LDAP-Authentication

That's the limit of our LDAP config implementation right now.  For all other LDAP inquiries, please post in the main repo.

**Comment by xxedgexx** [comment]
Yes, so I have the latest version built and I actually see the Administration option now and the ability to configure LDAP, but there isn't very much information, such as what is the format of the LDAP URL?  I'm trying ldaps://10.0.0.1/ for example.  I'm not sure exactly what is expected of the LDAP DN?  I'm trying to authenticate against a FreeIPA LDAP server.  Is there a way to set the Login attribute?  Maybe just an example of a working connection would help.

**Comment by Sing-Li** [comment]
Please post in main repo:

https://github.com/RocketChat/Rocket.Chat/issues/new

You will be able to get help there.  

Also, you may want to go to the demo chat, and look for @marceloschmidt   -   after tomorrow (Saturday Aug 22)  for direct questions.

**Comment by xxedgexx** [comment]
Thanks!  Submitted a request.
