### ISSUE TITLE
0.62.2 broken (crashes on startup)

### ISSUE THREAD

**Issue by micw** [RocketChat/Docker.Official.Image#40]
Hello,

I got this issue when I switched from 0.61.2 to 0.62.2: https://github.com/RocketChat/Rocket.Chat/issues/10114#issuecomment-372584837

The cause is a segmentation fault with node js 8.10: https://github.com/nodejs/node/issues/19274

The breaking change is between 0.62.0 and 0.62.1 docker image:

```
docker run --rm -it library/rocket.chat:0.62.0 node --version
v8.9.4
```

```
docker run --rm -it library/rocket.chat:0.62.1 node --version
v8.10.0
```

Proposed fix: use node version 8.9 as base image.

**Comment by sampaiodiego** [comment]
as stated at https://github.com/RocketChat/Rocket.Chat/issues/10114#issuecomment-372650473 I was able to run `0.62.2` .. do you have any additional details?

**Comment by micw** [comment]
I have created a copy of my environment and upgraded from 0.61.2 to 0.62.0 - the server started with no problems.

Then I upgraded to 0.62.1 - and it dies at the same point as before:

```
13.3.2018 19:14:39Will load cache for users
13.3.2018 19:14:3929 records load from users
13.3.2018 19:14:39Will load cache for rocketchat_room
13.3.2018 19:14:39180 records load from rocketchat_room
13.3.2018 19:14:39Will load cache for rocketchat_subscription
13.3.2018 19:14:39437 records load from rocketchat_subscription
13.3.2018 19:14:39Will load cache for rocketchat_settings
13.3.2018 19:14:39628 records load from rocketchat_settings
13.3.2018 19:14:42Updating process.env.MAIL_URL
13.3.2018 19:14:42Starting Email Intercepter...
```

**Comment by micw** [comment]
I downgraded again, enabled debug logging in admin view and upgraded to 0.62.2. Similar result:

```
13.3.2018 19:20:55Will load cache for users
13.3.2018 19:20:5529 records load from users
13.3.2018 19:20:55Will load cache for rocketchat_room
13.3.2018 19:20:55180 records load from rocketchat_room
13.3.2018 19:20:55Will load cache for rocketchat_subscription
13.3.2018 19:20:55437 records load from rocketchat_subscription
13.3.2018 19:20:55Will load cache for rocketchat_settings
13.3.2018 19:20:55628 records load from rocketchat_settings
13.3.2018 19:20:57BaseCache ➔ debug rocketchat_settings Falling back observe to model with query: undefined
13.3.2018 19:20:58BaseCache ➔ debug rocketchat_settings Falling back observe to model with query: undefined
13.3.2018 19:20:58Updating process.env.MAIL_URL
13.3.2018 19:20:58Starting Email Intercepter...
13.3.2018 19:20:59BaseCache ➔ debug rocketchat_settings Falling back observe to model with query: { _id: /theme-color-rc/i }
```

**Comment by micw** [comment]
I ran the container with a sleep command, attached a shell and executed "node main.js" in the shell. Same result as above plus one more log line:

> Segmentation fault

**Comment by sampaiodiego** [comment]
@micw this is weird.. please try removing your current image and pulling it again (`docker rmi rocket.chat:0.62.2` and `docker pull rocket.chat:0.62.2`).

if after that you end up with same issue, please try using our own image: `rocketchat/rocket.chat:0.62.2`

**Comment by micw** [comment]
Same with freshly pulled image. WIth rocketchat/rocket.chat:0.62.2 it works.- But that one uses node 8.9.3

```
14.3.2018 06:23:00➔ +--------------------------------------------------------------+
14.3.2018 06:23:00➔ |                        SERVER RUNNING                        |
14.3.2018 06:23:00➔ +--------------------------------------------------------------+
14.3.2018 06:23:00➔ |                                                              |
14.3.2018 06:23:00➔ |  Rocket.Chat Version: 0.62.2                                 |
14.3.2018 06:23:00➔ |       NodeJS Version: 8.9.3 - x64                            |
14.3.2018 06:23:00➔ |             Platform: linux                                  |
14.3.2018 06:23:00➔ |         Process Port: 3000                                   |
14.3.2018 06:23:00➔ |             Site URL: http://prod1.rancher.evermind.de:3000  |
14.3.2018 06:23:00➔ |     ReplicaSet OpLog: Disabled                               |
14.3.2018 06:23:00➔ |          Commit Hash: 07f0e3f77c                             |
14.3.2018 06:23:00➔ |        Commit Branch: HEAD                                   |
14.3.2018 06:23:00➔ |                                                              |
14.3.2018 06:23:00➔ +--------------------------------------------------------------+
```

**Comment by sampaiodiego** [comment]
Since it worked I've created a pull request to force image to use `8.9`.. let's see how it goes

**Comment by sampaiodiego** [comment]
looking at @micw logs again I noticed `ReplicaSet OpLog: Disabled` , so I tried again using this same configuration and it crashed to me as well.

I'll leave this closed and add this new info into https://github.com/RocketChat/Rocket.Chat/issues/10114 so we can keep talking there, as it not seems to be a docker image issue

**Comment by micw** [comment]
@sampaiodiego Seems to be the combination of "OpLog: Disabled" and node 8.10. So the docker workaround might be a good thing until the root cause is fixed.

**Comment by micw** [comment]
@sampaiodiego Seems to be the combination of "OpLog: Disabled" and node 8.10. So the docker workaround might be a good thing until the root cause is fixed.
