### ISSUE TITLE
User status change and join/leave messages not displayed

### ISSUE THREAD

**Issue by cybergrunge** [RocketChat/Docker.Official.Image#44]
I don't have messages displayed in the chat window when a user changes status (away, offline…), neither when a user joins or leaves the room, and I can't find any setting in the administration relative to this.

**Comment by pierreozoux** [comment]
how many app containers do you have? What is your setup?

**Comment by cybergrunge** [comment]
I have the mongo and the rocket containers running, behind an [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy/) container (alongside a [letsencrypt-nginx-proxy-companion](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/)), and an apache reverse proxy I set up to manage 443 <—> 3000 connection between nginx and rocket.

`letencrypt`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
`nginx` — `apache` — `rocket`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mongodb`

**Comment by geekgonecrazy** [comment]
Is this still an issue?  Going to close this.  But if it is we'll want to transfer this to main repo where it can get attention.  

But i'm guessing this was setup related
