### ISSUE TITLE
Just pulled new image push notifications not going out anymore?

### ISSUE THREAD

**Issue by vulcanjedi** [RocketChat/Docker.Official.Image#45]
Description: Push notifications suddently stopped working, iOS all users/devices (messages sent just not push notifications)
Server Setup Information: official docker image (ubuntu host) with nginx proxy and letsencrypt
Version of Rocket.Chat Server:latest 
Operating System: 0.63.2
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances:1
DB Replicaset Oplog: disabled
Node Version: v8.11.1
mongoDB Version: latest
Steps to Reproduce: Send Test notifcation via Admin console/gui; via mobile/thin client apps on mac/windows/ios.  
Expected behavior: Messages sent via channels/direct messages but also push notification banners on mobiles.
Actual behavior:
Messages received fine; no push notifications.
This was working perfectly.  Scripted calls working, notification agents working, webhook and channel override working.

I just recently got rocketchat up via Docker image/docker compose. After finally getting proxy sorted out everything was wonderful.
But did docker compose pull and docker compose up today and now while notifications sent, no push notifications are being fired?

**Comment by geekgonecrazy** [comment]
If this is still happening please let me know.  From the lack of updates here I'm going to assume this is a one off issue
