### ISSUE TITLE
Problem with rocketchat mails, smtp send an IP addres in HELO name

### ISSUE THREAD

**Issue by rfpolverini** [RocketChat/Docker.Official.Image#46]
HI, first, congratulations for this great proyect.
We have implemented time ago some rocketchat docker stack, with 

database image:   mongo:3.0  
rocketchat image: rocket.chat:latest	
https layer:      remynoulin/stud

we have a problem for send email with rocketchat, because the mail are arriving to exim4 with "an IP in HELO Name", as can you see in this line of log of our exim service (is in other server external of the docker stack) 
2018-04-20 11:43:11 H=xxx.members.linode.com ([127.0.0.1]) [74.xxx.xx.2xx] rejected MAIL <chat@bantics.com.ar>: Helo name contains a ip address (HELO was [127.0.0.1]) and not is valid
--

obviously if we comment the ACL in exim4 that reject a mail with an IP in HELO name, this mail is sended OK.

We saw changes in the smtp sections are done little time ago, and keeping in mind that we had worked with this rocketchat image time ago, with our exim smtp server,  we tried to dowgrade the rocket chat docker version to rocket.chat:0.50.1 in wich we saw difference in the smtp section (have not "ignore TLS" and "SMTP pool" options) but the mail arrive with the same "an IP in HELO Name".

We think that it can be a missconfiguration in our docker, but we cannot find the solution for this problem.

We launch the dockers in this order

docker run --restart=always --name example-rc-db -v /datos/docker/example/rc-db:/data/db -d mongo:3.0 --smallfiles
docker run --restart=always --name example-rc-chat --link example-rc-db:db -d rocket.chat:0.50.1
docker run --restart=always --name example-rc-stud -p 5443:443 --link example-rc-chat:app -v /datos/docker/example/rc-stud/certs:/opt/certs -d remynoulin/stud

as you can see, we are not exposing the port 3000 of rocketchat, we are only forwarding the 443 port of stud (HTTPS)
The rocketchat is working fine, the HTTPS certificate too, and its connect OK with mongodb, the only problem that we have is that when rocketchat send a mail, include ([127.0.0.1]) in the header, and we dont find any configuration for this.

We'll like to know if somebody more had for this problem and can solve it
THanks a lot
Best regards
Ramiro Polverini - Bantics Cooperativa

**Comment by mike-kfed** [comment]
I ran into this aswell. Meteor uses nodemailer, nodemailer uses 127.0.0.1 for HELO if the hostname of the machine has no '.' in it (see their `lib/smtp.js`), therefore the `--hostname` option of docker is important, just use `docker run --hostname with.a.dot --name blah ...`

**Comment by geekgonecrazy** [comment]
Might be worth adding as a note in docs.  

If you feel like this is an issue please open an issue on main repo.

**Comment by rfpolverini** [comment]
thanks a lot!!
