### ISSUE TITLE
FATAL ERROR: Zone Allocation failed - process out of memory  --- during import

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Docker.Official.Image#53]
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Tue, 24 Jul 2018 14:53:34 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at npm/node_modules/connect/lib/middleware/bodyParser.js:56:20
Tue, 24 Jul 2018 14:53:34 GMT connect deprecated limit: Restrict request size at location of read at npm/node_modules/connect/lib/middleware/multipart.js:86:15
FATAL ERROR: Zone Allocation failed - process out of memory
1: node::Abort() [node]
2: 0x121a2cc [node]
3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
5: v8::internal::Zone::New(unsigned long) [node]
6: v8::internal::compiler::SimplifiedOperatorBuilder::LoadField(v8::internal::compiler::FieldAccess const&) [node]
7: v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(v8::internal::compiler::Node*) [node]
8: v8::internal::compiler::JSTypedLowering::Reduce(v8::internal::compiler::Node*) [node]
9: v8::internal::compiler::GraphReducer::Reduce(v8::internal::compiler::Node*) [node]
10: v8::internal::compiler::GraphReducer::ReduceTop() [node]
11: v8::internal::compiler::GraphReducer::ReduceNode(v8::internal::compiler::Node*) [node]
12: v8::internal::compiler::TypedLoweringPhase::Run(v8::internal::compiler::PipelineData*, v8::internal::Zone*) [node]
13: v8::internal::compiler::PipelineImpl::CreateGraph() [node]
14: v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl() [node]
15: v8::internal::CompilationJob::PrepareJob() [node]
16: 0xdc6269 [node]
17: v8::internal::Compiler::CompileOptimized(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::ConcurrencyMode) [node]
18: v8::internal::Runtime_CompileOptimized_Concurrent(int, v8::internal::Object**, v8::internal::Isolate*) [node]
19: 0x1c0923b0463d

**Comment by pierreozoux** [comment]
Hi :)

Looks like your container or host server didn't have enough memory.

I'll close for now, but feel free to reopen if it was not the problem.
