### ISSUE TITLE
New version in Docker Hub

### ISSUE THREAD

**Issue by victorwpbastos** [RocketChat/Docker.Official.Image#58]
When the new version (0.71.1) will be available in Docker Hub?

**Comment by tianon** [comment]
Now that https://github.com/docker-library/official-images/pull/5020 is merged, 0.71.0 should be available shortly (as soon as it builds on the official servers).

I'll likely make a PR for 0.71.1 later today.

**Comment by lag-linaro** [comment]
0.71.1 is now available.  This Issue should be closed.
