### ISSUE TITLE
Docker Image is using Mongo in version 3.2, version 3.6 is recommended

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Docker.Official.Image#62]
Hello,
Currently Docker image is using Mongo 3.2, but the recommendation is to use version 3.6 or more. Please consider updating Docker Compose file to latest stable version.

**Comment by sampaiodiego** [comment]
thanks for the heads up.. the minimum working version is currently 3.2 though. But I'll update the description to 4.0 which is the recommended right now.

**Comment by lorek123** [comment]
3.2 is EOL since September 2018, so moving on from this version seems reasonable: 
https://www.mongodb.com/support-policy/
