### ISSUE TITLE
Latest tag in hub.docker.com is still 0.71.1

### ISSUE THREAD

**Issue by FrancoisBillant** [RocketChat/Docker.Official.Image#64]
Hello,

It seems that changes made in this repo are not mirrored on hub.docker.com.
Commit 49c5b9b says update to to 0.73.2  but latest tag on dockerhub is still 0.71.1 : https://hub.docker.com/_/rocket-chat?tab=tags&page=1
Latest comment in this issue (https://github.com/RocketChat/Docker.Official.Image/issues/61#issuecomment-450203444) is also mentioning this problem.

**Comment by d-gubert** [comment]
Hi

You can try to grab an image from our hub https://hub.docker.com/r/rocketchat/rocket.chat

**Comment by FrancoisBillant** [comment]
Yes sure. But what about the "official" "docker verified" image ?

The different images currently available on dockerhub are misleading.
There is somehow 2 "verified content" images : 
https://hub.docker.com/_/rocket-chat
https://hub.docker.com/_/rocketchat
Both of them being at at version 0.71.1
And there is the rocketchat user's image:
https://hub.docker.com/r/rocketchat/rocket.chat
which is up to date.

I personally would prefer the releases and updates to be done on the official image, which is the usual standard on dockerhub (and that only one image would be available).
But if rocket.chat wish to stick with the user images, then one should delete the official ones to avoid those misunderstandings and to be clear about the one and only official image to be used and maintained.

**Comment by d-gubert** [comment]
Yeah, I'm not really sure why the "official" images are not up to date, maybe @geekgonecrazy can provide more details on that

**Comment by alexxkn** [comment]
Hello. Any news on this issue? Official image is still not updated :-(

**Comment by d-gubert** [comment]
We're still waiting on Meteor 1.8.1 to be able to update the official image, as stated [here](https://github.com/RocketChat/Docker.Official.Image/pull/57#issuecomment-455644667)

**Comment by vwbusguy** [comment]
If it's helpful to anyone else, I was able to find newer releases at https://hub.docker.com/r/rocketchat/rocket.chat/tags .  Not sure what the differences may be in the Dockerfile, but I had no problem with simply using the rocketchat/rocket.chat images instead in the same openshift deployment setup.

**Comment by geekgonecrazy** [comment]
https://github.com/docker-library/official-images/pull/5490 as soon as this is merged we should be back up to current. 

With the official docker images you can only depend on other official images.   Because of this, when the node.js image was updated and the tag we needed was no longer on the supported list... our builds failed.

So we have now updated our image to depend instead on a debian base image and install node.js our selves.  Not ideal.. but gets us back on track.

Thanks for the patience!

**Comment by geekgonecrazy** [comment]
And live! https://hub.docker.com/_/rocket-chat?tab=description
