### ISSUE TITLE
RocketChat Dockerfile Build Issues

### ISSUE THREAD

**Issue by dijarllozana** [RocketChat/Docker.Official.Image#65]
I dont know if im just so bad at this but here's my issue: 
Im trying to build my own image of RocketChat so that i can push updates to it and re create images for Production

In this case im using this rocketchat repository that I can edit and then build from it, but it doesnt work.

Here is the repo im using: https://github.com/RocketChat/Rocket.Chat

Now i want to build with Dockerfile which is like this:

```
FROM rocketchat/base:8

ADD . /app
MAINTAINER buildmaster@rocket.chat

RUN set -x \
&&  cd app/bundle/programs/server \
&&  npm install \
&&  npm cache clear --force \
&&  chown -R rocketchat:rocketchat /app

VOLUME /app/uploads

USER rocketchat

WORKDIR /app/bundle

ENV DEPLOY_METHOD=docker \
    MONGO_URL=mongodb://mongo-test:27017/rocket \
    HOME=/tmp \
    PORT=3000 \
    ROOT_URL=http://localhost:3000 \
    Accounts_AvatarStorePath=/app/uploads

EXPOSE 3000

CMD ["node", "main.js"]

 ```

And the problem is that i dont know where its building from since i modify the Dockerfile which is located in ".docker" and i build with:
` docker build -t rocketchat:custom -f .docker/Dockerfile . `

the output is always the same:

```
Step 1/10 : FROM rocketchat/base:8
 ---> 1dc2a21e1890
Step 2/10 : ADD . /app
 ---> b71e563c6065
Step 3/10 : MAINTAINER buildmaster@rocket.chat
 ---> Running in bca3ee37f262
Removing intermediate container bca3ee37f262
 ---> 4c53e4e67565
Step 4/10 : RUN set -x &&  cd app/bundle/programs/server &&  npm install &&  npm cache clear --force &&  chown -R rocketchat:rocketchat /app
 ---> Running in efff8d296304
+ cd app/bundle/programs/server
/bin/sh: 1: cd: can't cd to app/bundle/programs/server
The command '/bin/sh -c set -x &&  cd app/bundle/programs/server &&  npm install &&  npm cache clear --force &&  chown -R rocketchat:rocketchat /app' returned a non-zero code: 2
 ```

While using ```ls``` in the Dockerfile, I see that there is no bundle directory so it cannot ```cd``` into it, but i dont know why its not building it. 
Thanks in advance!

**Comment by dijarllozana** [comment]
Sorry, im just stupid, first you have to build with Meteor and then obviously create the image from it, anyway, to build with meteor just see the commands in .circleci folder.

**Comment by d-gubert** [comment]
Closing the issue since you've been able to solve it.

And don't be so harsh on yourself! ;)
