### ISSUE TITLE
Configure MONGO_OPLOG_URL

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Docker.Official.Image#7]
We should make an effort to use MongoDB on ReplicaSET mode whenever possible, and configure the respective MONGO_OPLOG_URL. This has a MASSIVE impact on performance. Rocket.Char does not scale otherwise.

https://github.com/RocketChat/Deploy.to.Cloud/issues/23

**Comment by cpitman** [comment]
Does this require anything more than adding `ENV MONGO_OPLOG_URL=mongodb://db:27017/local` to the Dockerfile? Is there an additional complication?

**Comment by geekgonecrazy** [comment]
Closing this. Unfortunately can't really force this set.  Up to the person deploying to set this after they have converted to replicaset.

Our docs cover this
