### ISSUE TITLE
Broken Permissions in chown command for rocketchat

### ISSUE THREAD

**Issue by Borillion** [RocketChat/Docker.Official.Image#77]
Line number 28 in the Docker file has a mistake. Note the (.) dot between rocketchat,
needs to have a (:) colon.

&&  chown rocketchat.rocketchat /app/uploads

https://github.com/RocketChat/Docker.Official.Image/blob/fe7055833d24b876ff53a0fbcf5173006f8613c7/Dockerfile#L28

**Comment by snoopotic** [comment]
Well, a backwards-compatibility allows using a dot as delimiter for ‚chown‘. Sadly, usernames with a dot will have problems. But „rocketchat“ hasn‘t. So it‘s just a more or less cosmetic request.
