### ISSUE TITLE
Version out of date.

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Docker.Official.Image#8]
Can we keep this in sync more with the current version in the rocket.chat repo?

Looks like we're at least one version behind.  I've seen other docker images have a dev label.

**Comment by Sing-Li** [comment]
Yes. We will.

Each and every update and change goes through a review process, by the upper tier tech gurus at docker dot com. 

It can take up to a month of elapsed time.

We will bundle 0.5 and 1.0 when 1.0 is ready.

We also need to further automate our image build workflow.

**Comment by marceloschmidt** [comment]
@Sing-Li What can we do to make this process faster and automated? Do we have to create a new release every time we think it should be updated on docker official image? TIA

**Comment by Sing-Li** [comment]
@marceloschmidt   Yes, needs to create a build workflow (real one), so we need to:

* officially tag the release 
* build it and create the tgz
* sign it (gabriel has the official key)
* generate the docker file with the appropriate release version and location and signature files
* create and commit a new release (git hash to dockerfile and docs)  on the official docker registry
* submit the new hash set to the committee for review
* wait

**Comment by geekgonecrazy** [comment]
Wow! What a list! So all of this is essentially so it'll be verified as legit?  You'd think they would have an easier way to do this.  

Maybe we can automate some of this with chatops :)

**Comment by Sing-Li** [comment]
OK ... updating with v0.7  now that we have a real working CI/CD workflow.
