### ISSUE TITLE
unable to install without replica set for MongoDB

### ISSUE THREAD

**Issue by b-t-o** [RocketChat/Docker.Official.Image#80]
Starting In Release 1.0, Rocket.Chat requires the use of MongoDB REPLICASET to improve performance via Meteor Oplog tailing. (See [BREAK] Require OPLOG/REPLICASET to run Rocket.Chat #14227)

the current docker-compose file leads to 

> rocketchat_1  | ➔ +---------------------------------------------------------------------------+
rocketchat_1  | ➔ |                                SERVER ERROR                               |
rocketchat_1  | ➔ +---------------------------------------------------------------------------+
rocketchat_1  | ➔ |                                                                           |
rocketchat_1  | ➔ |  Rocket.Chat Version: 1.0.3                                               |
rocketchat_1  | ➔ |       NodeJS Version: 8.11.4 - x64                                        |
rocketchat_1  | ➔ |      MongoDB Version: 3.2.21                                              |
rocketchat_1  | ➔ |       MongoDB Engine: wiredTiger                                          |
rocketchat_1  | ➔ |             Platform: linux                                               |
rocketchat_1  | ➔ |         Process Port: 3000                                                |
rocketchat_1  | ➔ |             Site URL: https://chat.flinker-freddy.de                      |
rocketchat_1  | ➔ |     ReplicaSet OpLog: Disabled                                            |
rocketchat_1  | ➔ |          Commit Hash: f19473c626                                          |
rocketchat_1  | ➔ |        Commit Branch: HEAD                                                |
rocketchat_1  | ➔ |                                                                           |
rocketchat_1  | ➔ |  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
rocketchat_1  | ➔ |  https://go.rocket.chat/i/oplog-required                                  |

I think there is some change to docker-compose.yml nessesary

**Comment by brunowego** [comment]
Same issue here. Step by step to reproduce:

## Volume

```sh
docker volume create rocketchat-mongo-data
docker volume create rocketchat-uploads
```

## Running

```sh
docker run -d \
  -h mongo.rocketchat.local \
  -v rocketchat-mongo-data:/data/db \
  -e MONGO_INITDB_DATABASE=rocketchat \
  -p 27017:27017 \
  --name rocketchat-mongo \
  --restart always \
  mongo:4.1
```

```sh
docker run -d \
  -h app.rocketchat.local \
  -v rocketchat-uploads:/app/uploads \
  -e MONGO_URL=mongodb://rocketchat-mongo:27017/rocketchat \
  -p 3000:3000 \
  --name rocketchat-app \
  --restart always \
  --link rocketchat-mongo \
  rocket.chat:1.0.3
```

```sh
echo -e "[INFO]\thttp://$(docker-machine ip):3000"
```

## Remove

```sh
docker rm -f rocketchat-mongo rocketchat-app
docker volume rm rocketchat-mongo-data rocketchat-uploads
```
