### ISSUE TITLE
Rocket chat file storage ?

### ISSUE THREAD

**Issue by KenN7** [RocketChat/Docker.Official.Image#9]
Hi,

I used your image to install my rocket.chat instance, it works fine but i cannot manage to find
where the uploaded files and avatars are stored ?
I think there is a volume missing so that they would get saved if the image is restarted ?
Thanks,
Regards,

**Comment by Sing-Li** [comment]
Yes. @KenN7  Thank you for bringing this to our attention.

In the latest version, both uploaded files and avatars are stored into MongoDB via GridFS by default.  So any problem will go away.   

You can change the storage target settings in the administration panel; or you can try the rocketchat/Rocket.Chat image (updated frequently) if you need a fix quick.

**Comment by kev2316** [comment]
I am also running into a similar problem with version 0.58.3 using gridFS

error logs I receive are 

[Error: FileNotFound: no file with id vCDpXfD42Q4c2nRp4 found]

every time I try to upload a file from web or desktop app. Everything else seems to be working so I am confused what is causing this issue. I followed the instructions verbatim.

**Comment by geekgonecrazy** [comment]
Closing this.  Please see docs for file storage methods.  

https://github.com/RocketChat/docs/pull/1153

**Comment by farzadso** [comment]
@kev2316 Yes, changing the Site Url to it's correct value in Settings > General fixed the issue for me.
