### ISSUE TITLE
Feature request: option to run rocketchat disconnected without internet access

### ISSUE THREAD

**Issue by RonnyMaas** [RocketChat/Docker.Official.Image#90]
I would like to use rocketchat on-premise in an environment without internet access.
I used the rocketchat stable helm chart (multiple versions) to install rocketchat in kubernetes (kubespray 1.14.1)
Rocketchat wasn't able to start until I added extra args for http_proxy, https_proxy and no_proxy to the vars of the helm chart.

Took me a lot of time to find out why rocket chat would't start because there where no errors in the logs beside the health check fails for port 3000. And because of that the container kept restarting.

**Comment by reetp** [comment]
Please close this and open it in the correct place:

https://github.com/RocketChat/feature-requests/issues

You will find other Issues relating to offline installs if you hunt through the various repos.

**Comment by RonnyMaas** [comment]
created feature request #168
