### ISSUE TITLE
Missing image for RC 2.2

### ISSUE THREAD

**Issue by whedro** [RocketChat/Docker.Official.Image#94]
Hi, 
on DockerHub missing image with tag 2.2.

Thanx a lot
Michal

**Comment by alexxkn** [comment]
Do you have any updates on when this might be fixed?

**Comment by reetp** [comment]
What is missing from here?

https://hub.docker.com/r/rocketchat/rocket.chat/tags

**Comment by alexxkn** [comment]
We talk about Official Rocket.Chat docker deployment image.
Link https://hub.docker.com/_/rocket-chat?tab=tags

**Comment by sampaiodiego** [comment]
thanks guys for pointing this up, I have just submitted this PR https://github.com/docker-library/official-images/pull/6997 to update the official image :crossed_fingers:

**Comment by sampaiodiego** [comment]
The missing image was publish.. Thanks again guys.

**Comment by alexxkn** [comment]
@sampaiodiego Hi,
We are all waiting for the new version of image version 3. Again)
Could you push it to docker hub, please?

**Comment by sampaiodiego** [comment]
hi @alexxkn .. the plan is to release it with https://github.com/RocketChat/Docker.Official.Image/pull/106
